### PR TITLE
up

### PR DESCRIPTION
**Pull request by dct-LuLu**

### CODE REVIEW

**Comment by hhenrichsen** [comment]
Seems like this is replacing a lot of my template code with terminal specific code, in addition to things like changing the license and deleting some used files like the git hooks and such. What is this supposed to do? Can you clean up the git history so it is linear and descriptive?

**Review by hhenrichsen — CHANGES_REQUESTED** [review]
Marking this as needs work until there's a clear reason to replace the template with the terminal component's full code. Seems like you forked the template instead of just using the template.

**Comment by hhenrichsen** [comment]
Closing this as inactive.

**Comment by dct-LuLu** [comment]
Oh yes my bad that's what happened, I mistakenly forked the template instead of using it. It was my first time using template on Github. I'm gonna try and delete my repo wich fork the template and make a new one using the template.

**Pull request closed without merging**
